openapi: 3.1.0
x-stoplight:
  id: stuf38fx0a5yx
info:
  title: DotaDataUpdateAPI
  version: '1.0'
  description: Used to fill Database with up to date info about the game
  contact:
    name: Bogdan Yarotsky
servers:
  - url: 'http://localhost:3000'
paths:
  /update:
    post:
      summary: ''
      operationId: post-dota-update
      description: Add new Dota Update to the database
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update'
      responses:
        '200':
          description: OK
    parameters: []
  /patch:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patch'
      operationId: get-dota-patch
      description: Returns latest Dota patch
    parameters: []
  /heroes:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hero'
      operationId: get-dota-heroes
    parameters: []
  '/heroes/{gameId}':
    parameters:
      - schema:
          type: string
        name: gameId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
      operationId: get-dota-hero-gameId
  /items:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
      operationId: get-dota-items
    parameters: []
  '/items/{gameId}':
    parameters:
      - schema:
          type: string
        name: gameId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
      operationId: get-dota-items-gameId
components:
  schemas:
    Patch:
      title: DotaPatch
      x-stoplight:
        id: 7c0561wiybltm
      type: object
      additionalProperties: false
      properties:
        patch:
          type: string
        date:
          type: string
    Hero:
      type: object
      x-examples:
        example-1:
          id: 0
          name: string
          localized_name: string
      description: Info about Hero from the game
      additionalProperties: false
      properties:
        gameId:
          type: integer
        name:
          type: string
        internalName:
          type: string
      title: DotaHeroDto
    Item:
      type: object
      x-examples:
        example-1:
          id: 0
          name: string
          localized_name: string
          cost: 0
      description: Info about Item from the game
      additionalProperties: false
      properties:
        gameId:
          type: integer
        name:
          type: string
        internalName:
          type: string
        cost:
          type: integer
    Update:
      type: object
      x-examples:
        example-1:
          patch: string
          heroes:
            - id: 0
              name: string
              localized_name: string
          items:
            - id: 0
              name: string
              localized_name: string
              cost: 0
      examples:
        - patch: string
          heroes:
            - id: 0
              name: string
              localized_name: string
          items:
            - id: 0
              name: string
              localized_name: string
              cost: 0
      additionalProperties: false
      properties:
        patch:
          $ref: '#/components/schemas/DotaPatchDto'
        heroes:
          type: array
          items:
            $ref: '#/components/schemas/DotaHeroDto'
        items:
          type: array
          items:
            $ref: '#/components/schemas/DotaItemDto'
